config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'
  resources :books do
    resources :pages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :pages, dependent: :destroy
  
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :book
  has_one_attached :image
  validates :image, presence: true

  def previous
    Page.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    Page.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true
         has_many :books, dependent: :destroy
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :move_to_index, except: [:index, :show]


  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to root_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
  end


  private
  def book_params
    params.require(:book).permit(:title, :content).merge(user_id:current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.where(book_id: params[:book_id])
    @book = Book.find(params[:book_id])
  end

  def new
    @page = Page.new
    @book = Book.find(params[:book_id])
  end

  def create
    page = Page.new(page_params)
    if page.save
    redirect_to book_pages_path
    else
      @page = Page.new
      @book = Book.find(params[:book_id])
      render :new
    end
  end

  def show
    @page = Page.find(params[:id])
    @book = Book.find(params[:book_id])
    # ad = rand(10)
    # unless ad != 1
    #   #広告
    # end
  end

  def destroy
    page = Page.find(params[:id])
    page.destroy
    redirect_to book_pages_path
  end

  def edit
    @page = Page.find(params[:id])
    @book = Book.find(params[:book_id])
  end

  def update
    page = Page.find(params[:id])
    if page.update(page_params)
      redirect_to book_pages_path
    else
      render :edit
    end
  end


  private
  def page_params
    params.require(:page).permit(:title, :image, :number).merge(book_id: params[:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @book, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "タイトル" %>
      <%= form.text_area :content, placeholder: "説明", rows: "2" %>
      <%= form.submit "編集完了" %>
    <% end %>
      <%= link_to '削除', book_path(@book.id), method: :delete, class: "delete" %>
  </div>
</div>

app/views/books/index.html.erb
<div class="title">
</div>

<div class="page-marks">

</div>

<div class="books">
  <% @books.each do |book| %>
      <div class="book">
          <div class="book-title">
            <%= book.title %>
          </div>
        <div class="book-image">
          <%= link_to image_tag("note.png"), book_pages_path(book.id) %>
        </div>
      </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>本を作る</h3>
    <%= form_with(model: @book, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "タイトル" %>
      <%= form.text_area :content, placeholder: "説明" %>
      <%= form.submit "作成" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url();">
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_book_path(@book.id), method: :get %>
        </li>
      </ul>
    </div>
    <p><%= @book.title %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pagemarks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Pagemarks</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%=link_to "本を作る",new_book_path, class: "post"%>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with model: [@book,@page], local: true do |form| %>
      <%= form.text_field :title, placeholder: "本のタイトル" %>
      <%= form.text_field :number, placeholder: "ページ" %>
      <%= form.file_field :image, placeholder: "画像" %>
      <%= form.submit "編集完了" %>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<div class="pages-index">
<div clas="pages-link">
<br>
  <%= link_to "ページを追加する", new_book_page_path, class: "page-new"%>
  <%= link_to '編集', edit_book_path(@book.id), class: "page-edit"%>
</div>
  <div class="pages">
    <% @pages.each do|page|%>
      <div class="page">
        <div class="page-top">
          <%= link_to (image_tag page.image.variant(resize: '300x250')), "pages/#{page.id}", class: "page-image" %>
        </div>
        <div class="page-top">
          <%= page.title %>
          <%= "：#{page.number}ページ" %>
        </div>
      </div>   
    <% end %>
  </div> 
</div>

app/views/pages/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with model: [@book,@page], local: true do |form| %>
      <%= form.text_field :title, placeholder: "本のタイトル" %>
      <%= form.text_field :number, placeholder: "ページ" %>
      <%= form.file_field :image, placeholder: "画像" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/pages/show.html.erb
<div class="page-show">
  <br>
  <div class=page-link>
    <%= link_to link_to "戻る", book_pages_path(@book.id) , class: "page-return"%>
    <%= link_to '削除', "#{@page.id}", method: :delete, class: "page-delete"%>
    <%= link_to '編集', edit_book_page_path, class: "page-edit"%>
  </div>
    <div class="page-top">
      <p class="page-title"><%= @page.title %></p>
      <p class="page-number"><%= "#{@page.number}ページ" %></p>
    </div>
    <div class="page-image">
      <% if @page.previous.present? %>
        <%= link_to image_tag("left.png"), book_page_path(@book,@page.previous), class: "btn_arrow_back"%>
      <% end %>
      <%= image_tag @page.image.variant(resize: '900x750'), class: "page-image" %>
      <% if @page.next.present? %>
       <%= link_to image_tag("right.png"),book_page_path(@book,@page.next), class: "btn_arrow" %>
      <% end %>
    </div>

</div>